# Configuration for librarian-puppet.
forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "puppetlabs/vcsrepo"

mod "puppetlabs/java", :git => "https://github.com/puppetlabs/puppetlabs-java"

#mod "storm-install", :path => "/puppet/local-modules/storm-install"
#mod "kettle-storm-install", :path => "/puppet/local-modules/kettle-storm-install"
